#!/usr/bin/env python3
"""Targeted, idempotent PT-BR fixes where language-independent logic is safer than translation."""
from __future__ import annotations

import codecs
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEYLINE = ROOT / "repo" / "js" / "AutoLeyLineOutcrop" / "utils" / "attemptReward.js"
CRYSTALFLY = ROOT / "repo" / "js" / "CrystalflyTrap" / "main.js"
MULTI_PATHING = ROOT / "repo" / "js" / "AutoPathingLoader-MultiUser" / "main.js"


def read(path: Path):
    raw = path.read_bytes()
    return raw.decode("utf-8-sig"), raw, raw.startswith(codecs.BOM_UTF8)


def write_like(path: Path, text: str, raw: bytes, bom: bool):
    newline = "\r\n" if b"\r\n" in raw else "\n"
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    data = normalized.replace("\n", newline).encode("utf-8")
    path.write_bytes((codecs.BOM_UTF8 if bom else b"") + data)


def collapse_numeric_classifier_wrapper(text: str, subject: str, amount: str) -> str:
    """Replace a localized Chinese classifier wrapper with the language-neutral number.

    ptbr_apply_textmap.py may first turn ``t.text.includes("20个")`` into a
    textContainsLiteral fallback expression. The numeric value itself is enough
    when it is combined with the localized full Resina Original label, so the
    wrapper must collapse cleanly on repeated migration passes.
    """
    escaped_subject = re.escape(subject)
    pattern = re.compile(
        rf'\(genshin\.textContainsLiteral\s*\?\s*'
        rf'genshin\.textContainsLiteral\({escaped_subject},\s*"{amount}个"\)\s*:\s*'
        rf'{escaped_subject}\.includes\("{amount}个"\)\)'
    )
    return pattern.sub(f'{subject}.includes("{amount}")', text)


def patch_leyline(text: str) -> str:
    text = text.replace(
        'const match = texts[i].text.match(/2倍产出次数[:：]?(\\d+)/);',
        'const match = texts[i].text.match(/(\\d+)/);'
    )
    text = text.replace(
        'if ((text.includes("20") || text.includes("20个")) && text.includes((genshin.getText ? genshin.getText("original_resin") : "原粹树脂"))) {',
        'if (text.includes("20") && text.includes((genshin.getText ? genshin.getText("original_resin") : "原粹树脂"))) {'
    )
    text = text.replace(
        'if ((text.includes("40") || text.includes("40个")) && text.includes((genshin.getText ? genshin.getText("original_resin") : "原粹树脂"))) {',
        'if (text.includes("40") && text.includes((genshin.getText ? genshin.getText("original_resin") : "原粹树脂"))) {'
    )

    # This source file uses CRLF. The previous literal multiline replacement only
    # matched LF, which left the final split Chinese "原粹"/"树脂" check behind.
    verify_pattern = re.compile(
        r'return\s+texts\.some\(t\s*=>\s*\r?\n\s*'
        r'\(t\.text\.includes\(targetAmount\.toString\(\)\)\s*&&\s*t\.text\.includes\("原粹"\)\)\s*\|\|\s*\r?\n\s*'
        r'\(t\.text\.includes\(`\$\{targetAmount\}个`\)\s*&&\s*t\.text\.includes\("树脂"\)\)\s*\r?\n\s*\);'
    )
    verify_replacement = (
        'const originalResin = genshin.getText ? genshin.getText("original_resin") : "原粹树脂";\n'
        '    return texts.some(t => t.text.includes(targetAmount.toString()) && t.text.includes(originalResin));'
    )
    text = verify_pattern.sub(verify_replacement, text)

    text = text.replace(
        'genshin.textContainsLiteral(t.text, "浓缩树脂") : t.text.includes("浓缩树脂")) || t.text.includes("浓缩"))',
        'genshin.textContainsLiteral(t.text, "浓缩树脂") : t.text.includes("浓缩树脂")))'
    )
    text = text.replace(
        'genshin.textContainsLiteral(t.text, "须臾树脂") : t.text.includes("须臾树脂")) || t.text.includes("须臾"))',
        'genshin.textContainsLiteral(t.text, "须臾树脂") : t.text.includes("须臾树脂")))'
    )
    text = text.replace(
        'genshin.textContainsLiteral(t.text, "脆弱树脂") : t.text.includes("脆弱树脂")) || t.text.includes("脆弱"))',
        'genshin.textContainsLiteral(t.text, "脆弱树脂") : t.text.includes("脆弱树脂")))'
    )
    text = text.replace(
        't.text.includes((genshin.getTextLiteral ? genshin.getTextLiteral("原石") : "原石")) && t.text.includes("3次")',
        't.text.includes((genshin.getTextLiteral ? genshin.getTextLiteral("原石") : "原石")) && t.text.includes("3")'
    )
    text = text.replace(
        'if (text === "使用") {',
        'if (genshin.textEqualsLiteral ? genshin.textEqualsLiteral(text, "使用") : text === "使用") {'
    )

    # Collapse wrappers generated by ptbr_apply_textmap.py. This is intentionally
    # done after the older source-shape replacements so the transform remains
    # idempotent regardless of which migration step ran first.
    for subject in ("t.text", "text"):
        for amount in ("20", "40"):
            text = collapse_numeric_classifier_wrapper(text, subject, amount)

        text = re.sub(
            rf'\({re.escape(subject)}\.includes\("20"\)\s*\|\|\s*\(genshin\.textContainsLiteral \? genshin\.textContainsLiteral\({re.escape(subject)}, "20个"\) : {re.escape(subject)}\.includes\("20个"\)\)\)',
            f'{subject}.includes("20")', text
        )
        text = re.sub(
            rf'\({re.escape(subject)}\.includes\("40"\)\s*\|\|\s*\(genshin\.textContainsLiteral \? genshin\.textContainsLiteral\({re.escape(subject)}, "40个"\) : {re.escape(subject)}\.includes\("40个"\)\)\)',
            f'{subject}.includes("40")', text
        )

    # Clean duplicate numeric branches produced by earlier migration passes.
    for amount in ("20", "40"):
        text = text.replace(
            f'({{"text" if False else "text"}}.includes("{amount}") || text.includes("{amount}"))',
            f'text.includes("{amount}")'
        )
        text = text.replace(
            f'(t.text.includes("{amount}") && t.text.includes((genshin.getText ? genshin.getText("original_resin") : "原粹树脂"))) ||\r\n            (t.text.includes("{amount}") && t.text.includes((genshin.getText ? genshin.getText("original_resin") : "原粹树脂")))',
            f't.text.includes("{amount}") && t.text.includes((genshin.getText ? genshin.getText("original_resin") : "原粹树脂"))'
        )
    text = text.replace('(text.includes("20") || text.includes("20"))', 'text.includes("20")')
    text = text.replace('(text.includes("40") || text.includes("40"))', 'text.includes("40")')
    return text


def patch_crystalfly(text: str) -> str:
    old_tab = '''            let backpackTitle = captureGameRegion();
            let resList = backpackTitle.findMulti(RecognitionObject.ocr(130, 0, 200, 50));
            backpackTitle.dispose();
            for (let i = 0; i < resList.count; i++) {
                let res = resList[i];
                if (!res.text.includes("小道")) {
                    log.info("点击小道具栏");
                    click(1060, 40);
                    await sleep(1000);
                }
            }'''
    new_tab = '''            // Open the gadget tab directly; this avoids a language-specific backpack title OCR check.
            log.info("点击小道具栏");
            click(1060, 40);
            await sleep(1000);'''
    text = text.replace(old_tab, new_tab)

    guard = re.compile(r'(?m)^\s*if \([^\n]*"晶蝶"[^\n]*"诱捕"[^\n]*"装置"[^\n]*\) \{$')
    replacement = '''                const isCrystalfly = genshin.textContainsLiteral ? genshin.textContainsLiteral(res.text, "晶蝶") : res.text.includes("晶蝶");
                const isDevice = genshin.textContainsLiteral ? genshin.textContainsLiteral(res.text, "装置") : res.text.includes("装置");
                if (!isCrystalfly || !isDevice) {'''
    text = guard.sub(replacement, text)
    return text


def patch_multi_pathing(text: str) -> str:
    # These are protocol messages exchanged by script instances through party chat.
    # Stable ASCII tokens are language-independent and OCR-friendly under both Latin
    # and Chinese Paddle models. Replace both normal strings and template literals
    # because the sender historically used a backtick while receivers used quotes.
    protocol = {
        "校验完成": "BGI_VERIFY_OK",
        "校验失败": "BGI_VERIFY_FAIL",
        "路线启动": "BGI_ROUTE_START",
        "全部路线结束": "BGI_ROUTES_DONE",
    }
    for old, new in protocol.items():
        for quote in ('"', "'", '`'):
            text = text.replace(f'{quote}{old}{quote}', f'{quote}{new}{quote}')
    return text


def main() -> int:
    changed = []
    for path, patcher in (
        (LEYLINE, patch_leyline),
        (CRYSTALFLY, patch_crystalfly),
        (MULTI_PATHING, patch_multi_pathing),
    ):
        text, raw, bom = read(path)
        updated = patcher(text)
        if updated != text:
            write_like(path, updated, raw, bom)
            changed.append(path.relative_to(ROOT).as_posix())
    print(f"Targeted PT-BR fixes changed {len(changed)} files: {changed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
